#!/bin/bash

#################################################################################################
#					ENVIRONMENT						#
#################################################################################################
[[ -n $DEBUG ]] && [[ $DEBUG != 0 ]] && set -x

export TEXTDOMAINDIR=@TEXTDOMAINDIR@
export TEXTDOMAIN=dmg2dir
prgname="dmg2dir"
issueurl="https://github.com/X0rg/dmg2dir/issues"
siteurl="https://github.com/X0rg"
udiskcmd=$(command -v udisksctl)
geniso=$(command -v genisoimage)
darling=$(command -v dyld)
version="3.0.3"
critical=0
fail=false

name=			# -n
savepath=		# -p
tmpdir="/tmp/$prgname"	# -t
run=false		# -r
iso=false		# -i
noappdir=false		# -d
quiet=			# -q
verbose1=		# -v
verbose2=		# -vv
overwriteimg=false	# --overwrite-img
overwritedir=false	# --overwrite-dir
overwriteiso=false	# --overwrite-iso


#################################################################################################
#					COMMONS	FUNCTIONS					#
#################################################################################################
msg() {
	local str="$1"

	if ! [[ -n "$quiet" ]]; then
		shift
		printf "\033[1;32m==>\033[0;1m $(gettext -s "$str")\033[0m\n" "$@"
	fi
}

msgverbose1() {
	local str="$1"

	if [[ -n "$verbose1" ]]; then
		shift
		printf "\033[1;34m  ->\033[0m $(gettext -s "$str")\n" "$@"
	fi
}

msgverbose2() {
	local str="$1"

	if [[ -n "$verbose2" ]]; then
		shift
		printf "    $(gettext -s "$str")\n" "$@"
	fi
}

msgwarning() {
	local str="$1"

	shift
	printf "\033[1;33m$(gettext -s "$str")\033[0m\n" "$@"
}

msgerror() {
	local error="$1"
	local str="$2"

	if ! $fail; then
		fail=true
		shift
		shift

		printf "\033[1;31m$(gettext -s "$str")\033[0m" "$@"
		printf "\033[1;31m$(gettext -s ' (error %i).')\033[0m\n" "$error"

		# Clean
		$iso && rm -rf $verbose1 "$vtree"

		if [[ $critical == 2 ]] ; then
			for part in ${loop}p*; do
				umountpart $part
			done
		fi

		if [[ $critical > 0 ]] ; then
			delloop
		fi
	fi

	exit $error
}

usage() {
	gettext -es "Usage: %s [OPTIONS] dmg_file.dmg"
	gettext -es "Options:"
	gettext -es "\t-n, --name\t\tCustom name for application directory"
	gettext -es "\t-p, --path\t\tCustom path for application directory"
	gettext -es "\t-t, --tmp\t\tCustom temporary directory"
	gettext -es "\t-r, --run\t\tAttempt to run extracted application (using Darling)"
	gettext -es "\t-i, --iso\t\tGenerate an ISO file from IMG file (using Genisoimage)"
	gettext -es "\t-d, --iso-only\t\tSame as --iso, without creating application directory"
	gettext -es "\t-q, --quiet\t\tBe silent"
	gettext -es "\t-v, --verbose\t\tBe verbose (-vv for very verbose)"
	gettext -es "\t-V, --version\t\tDisplay script version and exit"
	gettext -es "\t-h, --help\t\tDisplay this help and exit"
	gettext -es "\t    --overwrite-img\t\tOverwrite existing IMG file"
	gettext -es "\t    --overwrite-dir\t\tOverwrite existing application directory"
	gettext -es "\t    --overwrite-iso\t\tOverwrite existing ISO file"
	printf "$(gettext -s '\nPlease report issues here: %s.\n')" "$issueurl"
}

version() {
	echo -e "$prgname $version"
	echo -e "Copyleft 2018."
	echo -e "$siteurl"
}


#################################################################################################
#					VERIFIES FUNCTIONS					#
#################################################################################################
checkdep() {
	local command="$1"
	local depname="$2"
	local code="$3"

	if [[ -z "$command" ]]; then
		msgerror "$code" "Dependency %s is required" "$depname"
	fi
}

checkfile() {
	local file="$1"
	local code="$2"

	if [[ ! -f "$file" ]]; then
		msgerror "$code" "File %s doesn't exist" "$file"
	fi
}

checkvar() {
	local var="$1"
	local code="$2"

	if [[ -z "$var" ]]; then
		msgerror "$code" "Variable is empty"
	fi
}

checkdir() {
	local directory="$1"
	local code="$2"

	if [[ ! -d "$directory" ]]; then
		msgerror "$code" "Directory %s doesn't exist" "$directory"
	elif [[ -z "$(ls -A $directory)" ]]; then
		msgerror "$code" "Directory %s is empty" "$directory"
	fi
}

checkret() {
	local ret="$1"
	local code="$2"

	if [[ $ret != 0 ]]; then
		msgerror "$code" "Command fails"
	fi
}


#################################################################################################
#					MAIN FUNCTIONS						#
#################################################################################################
convertdmg() {
	msgverbose1 "Converting %s to %s" "$filetoconvert" "$tmpdir/$name.img"
	dmg2img $quiet $verbose1 $verbose2 -i "$filetoconvert" -o "$tmpdir/$name.img"
	checkret "$?" 10
	checkfile "$tmpdir/$name.img" 11
}

addloop() {
	msgverbose1 "Setting up loop device for file %s" "$tmpdir/$name.img"
	loop=$($udiskcmd loop-setup --no-user-interaction --read-only --file "$tmpdir/$name.img")
	checkvar "$loop" 20
	msgverbose2 "$loop"
	critical=1

	msgverbose1 "Retrieving loop device name"
	loop=${loop%.}
	loop=${loop#*/dev/loop}
	checkvar "$loop" 21
	loop="/dev/loop$loop"
	msgverbose2 "$loop"
}

mountpart() {
	local part=$1

	mountpoint=$(findmnt --noheadings --output TARGET $part)
	if [[ -z "$mountpoint" ]]; then
		msgverbose1 "Mounting loop device partition %s" "$part"
		$udiskcmd mount --block-device $part > $output
		mountpoint=$(findmnt --noheadings --output TARGET $part)
	fi
	checkvar "$mountpoint" 30
	msgverbose2 "$mountpoint"
	critical=2

	if $iso; then
		local label=$(basename "$mountpoint")
		msgverbose1 "Creating virtual tree %s" "$tmpdir/$name/$label"
		ln -sf $verbose1 "$mountpoint" "$tmpdir/$name/$label"
	fi
}

copydir() {
	msgverbose1 "Copying files from %s to application directory" "$mountpoint"
	cp -Rau $verbose1 "$mountpoint" "$appdir"
	checkdir "$appdir" 40
}

convertiso() {
	[[ -n "$quiet" ]] && local genisoquiet="-quiet"

	msgverbose1 "Generating ISO file from virtual tree %s" "$vtree"
	$geniso $genisoquiet $verbose1 -V "$name" -iso-level 3 -UDF -R -probe -g -posix-L -o "$appdir.iso" "$vtree"
	checkfile "$appdir.iso" 50
}

umountpart() {
	local part=$1

	msgverbose1 "Unmounting loop device partition %s" "$part"
	$udiskcmd unmount --no-user-interaction --force --block-device $part > $output
	checkret "$?" 60
	critical=1
}

delloop() {
	if [[ -f $loop* ]]; then
		msgverbose1 "Deleting loop device %s" "$loop"
		$udiskcmd loop-delete --no-user-interaction --block-device $loop > $output
		checkret "$?" 70
	fi
	critical=0
}

launcher() {
	msgverbose1 "Searching for executable in application directory"
	find "$appdir"/*/*.app/Contents/MacOS -exec file '{}' \; | grep "Mach-O" | grep "executable" | cut -f1 -d: | while IFS= read -r executable; do
		msgverbose1 "Found file %s, launch it with dyld" "$executable"
		dyld "$executable"
	done
}


#################################################################################################
#					MAIN							#
#################################################################################################
# Args
OPTS=`getopt -o n:p:t:ridqvwVh --long name:,path:,tmp:,run,iso,iso-only,quiet,verbose,version,help,overwrite-img,overwrite-dir,overwrite-iso -n $prgname -- "$@"`
if [[ $? != 0 ]]; then
	msgerror 1 "Failed parsing options"
fi

eval set -- "$OPTS"
while true; do
	case "$1" in
		-n|--name)		shift; name="$1";;
		-p|--path)		shift; savepath="$1";;
		-t|--tmp)		shift; tmpdir="$1";;
		-r|--run)		checkdep "$darling" "Darling" 1; run=true;;
		-i|--iso)		checkdep "$geniso" "cdrtools/cdrkit" 1; iso=true;;
		-d|--iso-only)		checkdep "$geniso" "cdrtools/cdrkit" 1; iso=true; noappdir=true;;
		-q|--quiet)		quiet="-s";;
		-v|--verbose)		unset quiet; [[ -z $verbose1 ]] && verbose1="-v" || verbose2="-V";;
		-V|--version)		version; exit 0;;
		-h|--help)		usage; exit 0;;
		--overwrite-img)	overwriteimg=true;;
		--overwrite-dir)	overwritedir=true;;
		--overwrite-iso)	overwriteiso=true;;
		--)			shift; break;;
		*)			gettext -es "Internal error"; exit 1;;
	esac
	shift
done

# Prerequisites
msg "Checking prerequisites..."
filetoconvert="$1"
if [[ -z "$filetoconvert" ]]; then
	usage
	exit 1
fi
if [[ ! -f "$filetoconvert" ]]; then
	msgerror 2 "File %s doesn't exist" "$filetoconvert"
fi
checkdep "$udiskcmd" "udisks2" 1

# Variables
msg "Setting variables..."
[[ -z "$name" ]] && name=$(basename "$filetoconvert" .dmg)
[[ -z "$savepath" ]] && savepath=$(dirname "$filetoconvert")
[[ -z "$verbose2" ]] && output="/dev/null" || output="/dev/stdout"
appdir="$savepath/$name"
vtree="$tmpdir/$name"

if ! $noappdir && ! $overwritedir && [[ -e "$appdir" ]]; then
	msgerror 3 "Directory %s already exists. Use --overwrite-dir to overwrite it" "$appdir"
fi
if $iso && ! $overwriteiso && [[ -e "$appdir.iso" ]]; then
	msgerror 4 "File %s already exists. Use --overwrite-iso to overwrite it" "$appdir.iso"
fi

# Temporary directories
msg "Making temporary working directories..."
mkdir -p $verbose1 "$tmpdir"
$iso && mkdir -p $verbose1 "$vtree"

# Conversion
msg "Converting DMG file to an IMG file..."
if [[ ! -f "$tmpdir/$name.img" ]] || $overwriteimg; then
	convertdmg
else
	msgwarning "File %s already exists. Skipping conversion. Use --overwrite-img to overwrite it." "$tmpdir/$name.img"
fi

# Mount
msg "Setting loop device..."
addloop
for part in ${loop}p*; do
	mountpart $part
done

# Extraction (directory)
if ! $noappdir; then
	msg "Extracting files to %s..." "$appdir"
	mkdir -p $verbose1 "$appdir"
	for part in ${loop}p*; do
		copydir
	done
fi

# Extraction (ISO)
if $iso; then
	msg "Creating ISO file %s..." "$appdir.iso"
	convertiso
fi

# Clean
msg "Cleaning..."
$iso && rm -rf $verbose1 "$vtree"
for part in ${loop}p*; do
	umountpart $part
done
delloop

# Run
if $run && ! $noappdir; then
	msg "Trying to run extracted application with Darling..."
	launcher
fi

exit 0

# Written by Xorg (https://github.com/X0rg/dmg2dir). Copyleft 2018.
